apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    # 在同一 docker 网络内通过容器名访问 prometheus
    url: http://prometheus:9090
    isDefault: true
    editable: true
