// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type GetUserInfoReq struct {
	UserId string `json:"user_id,optional"`
}

type GetUserInfoRsp struct {
	UserId string `json:"user_id"`
}

type HealthReq struct {
}

type HealthRsp struct {
}
