// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type BanPayReq struct {
	TransactionId string `json:"transaction_id,optional"` // 交易单号(由预交易接口返回)
	OutOrderNo    string `json:"out_order_no,optional"`   // 商户订单号
	MerchantId    string `json:"merchant_id,optional"`    // 商户ID
	UserId        string `json:"user_id,optional"`        // 用户ID
	Amount        int64  `json:"amount,optional"`         // 支付金额, 单位分
	VerifyType    int32  `json:"verify_type,optional"`    // 验证方式: 1密码
	Password      string `json:"password,optional"`       // 支付密码
}

type BanPayRsp struct {
	TransactionId     string `json:"transaction_id"`      // 交易单号
	OutOrderNo        string `json:"out_order_no"`        // 商户订单号
	MerchantId        string `json:"merchant_id"`         // 商户ID
	UserId            string `json:"user_id"`             // 用户ID
	Amount            int64  `json:"amount"`              // 支付金额, 单位分
	PayTime           string `json:"pay_time"`            // 支付完成时间
	OrderSuccessToken string `json:"order_success_token"` // 支付成功凭证token
}

type Bank2CDoReq struct {
	TransactionId string `json:"transaction_id,optional"` // 交易单号(由预交易接口返回)
	UserId        string `json:"user_id,optional"`        // 用户ID
	BankType      int32  `json:"bank_type,optional"`      // 银行类型/银行编码
	Amount        int64  `json:"amount,optional"`         // 充值金额, 单位分
	VerifyType    int32  `json:"verify_type,optional"`    // 验证方式: 1密码
	Password      string `json:"password,optional"`       // 支付密码
	Memo          string `json:"desc,optional"`           // 交易备注
}

type Bank2CDoRsp struct {
	TransactionId string `json:"transaction_id"` // 交易单号
	UserId        string `json:"user_id"`        // 用户ID
	IsRepeat      int32  `json:"is_repeat"`      // 是否成功且重入: 0否 1是(幂等命中)
}

type Bank2CPreReq struct {
	UserId string `json:"user_id,optional"` // 用户ID
}

type Bank2CPreRsp struct {
	UserId        string `json:"user_id"`        // 用户ID
	TransactionId string `json:"transaction_id"` // 预交易生成的交易单号
}

type C2BankDoReq struct {
	TransactionId string `json:"transaction_id,optional"` // 交易单号(由预交易接口返回)
	UserId        string `json:"user_id,optional"`        // 用户ID
	BankType      int32  `json:"bank_type,optional"`      // 银行类型/银行编码
	Amount        int64  `json:"amount,optional"`         // 提现金额, 单位分
	VerifyType    int32  `json:"verify_type,optional"`    // 验证方式: 1密码
	Password      string `json:"password,optional"`       // 支付密码
	Memo          string `json:"memo,optional"`           // 交易备注
}

type C2BankDoRsp struct {
	TransactionId string `json:"transaction_id"` // 交易单号
	UserId        string `json:"user_id"`        // 用户ID
	IsRepeat      int32  `json:"is_repeat"`      // 成功且重入: 0否 1是(幂等命中)
}

type C2BankPreReq struct {
	UserId string `json:"user_id,optional"` // 用户ID
}

type C2BankPreRsp struct {
	UserId        string `json:"user_id"`        // 用户ID
	TransactionId string `json:"transaction_id"` // 预交易生成的交易单号
}

type C2CTransferDoReq struct {
	TransactionId string `json:"transaction_id,optional"` // 交易单号(由预交易接口返回)
	BuyerUserId   string `json:"buyer_user_id,optional"`  // 付款方用户ID
	SellerUserId  string `json:"seller_user_id,optional"` // 收款方用户ID
	Amount        int64  `json:"amount,optional"`         // 转账金额, 单位分
	VerifyType    int32  `json:"verify_type,optional"`    // 验证方式: 1密码
	Password      string `json:"password,optional"`       // 支付密码
	Version       int32  `json:"version,optional"`        // 版本控制
	Memo          string `json:"memo,optional"`           // 备注
}

type C2CTransferDoRsp struct {
	TransactionId string `json:"transaction_id"` // 交易单号
	BuyerUserId   string `json:"buyer_user_id"`  // 付款方用户ID
	SellerUserId  string `json:"seller_user_id"` // 收款方用户ID
	IsRepeat      int32  `json:"is_repeat"`      // 成功且重入: 0否 1是(幂等命中)
}

type C2CTransferPreReq struct {
	BuyerUserId string `json:"buyer_user_id,optional"` // 付款方用户ID
}

type C2CTransferPreRsp struct {
	BuyerUserId   string `json:"buyer_user_id"`  // 付款方用户ID
	TransactionId string `json:"transaction_id"` // 预交易生成的交易单号
}

type CloseOrSupplyOrderReq struct {
	TransactionId string `json:"transaction_id,optional"` // 交易单号
	OutOrderNo    string `json:"out_order_no,optional"`   // 商户订单号
	MerchantId    string `json:"merchant_id,optional"`    // 商户ID
	UserId        string `json:"user_id,optional"`        // 用户ID
	Amount        int64  `json:"amount,optional"`         // 订单金额, 单位分
}

type CloseOrSupplyOrderRsp struct {
	ResultCode        int32  `json:"result_code"`         // 处理结果码: 1订单成功 2订单关闭
	TransactionId     string `json:"transaction_id"`      // 交易单号
	OutOrderNo        string `json:"out_order_no"`        // 商户订单号
	MerchantId        string `json:"merchant_id"`         // 商户ID
	UserId            string `json:"user_id"`             // 用户ID
	Amount            int64  `json:"amount"`              // 订单金额, 单位分
	PayTime           string `json:"pay_time"`            // 支付完成时间
	OrderSuccessToken string `json:"order_success_token"` // 支付成功凭证token
}

type GetC2CBillReq struct {
	TransactionId string `json:"transaction_id,optional"` // 交易单号
}

type GetC2CBillRsp struct {
	TransactionId string `json:"transaction_id"` // 交易单号
	BuyerUserId   string `json:"buyer_user_id"`  // 付款方用户ID
	SellerUserId  string `json:"seller_user_id"` // 收款方用户ID
	PayTime       string `json:"pay_time"`       // 支付时间
	Amount        int64  `json:"amount"`         // 交易金额, 单位分
	Desc          string `json:"desc"`           // 交易描述
	Memo          string `json:"memo"`           // 交易备注
}

type GetOrderInfoReq struct {
	TransactionId string `json:"transaction_id,optional"` // 交易单号
}

type GetOrderInfoRsp struct {
	TransactionId string `json:"transaction_id"` // 交易单号
	OutOrderNo    string `json:"out_order_no"`   // 商户订单号
	MerchantId    string `json:"merchant_id"`    // 商户ID
	MerchantName  string `json:"merchant_name"`  // 商户名称
	UserId        string `json:"user_id"`        // 用户ID
	Amount        int64  `json:"amount"`         // 订单金额, 单位分
	PayTime       string `json:"pay_time"`       // 支付完成时间
	TradeState    int32  `json:"trade_state"`    // 交易状态: 如待支付/成功/关闭/退款
}

type GetUserBalanceInfoReq struct {
	UserId string `json:"user_id,optional"` // 用户ID
}

type GetUserBalanceInfoRsp struct {
	UserId  string `json:"user_id"`  // 用户ID
	Balance int64  `json:"balance"`  // 账户余额, 单位分
	CurType int32  `json:"cur_type"` // 币种: 1人民币
}

type GetUserFlowReq struct {
	UserId string `json:"user_id,optional"` // 用户ID
	Offset int32  `json:"offset,optional"`  // 分页偏移量(从0开始)
	Limit  int32  `json:"limit,optional"`   // 单页返回条数
}

type GetUserFlowRsp struct {
	UserId       string     `json:"user_id"`      // 用户ID
	NextOffset   int32      `json:"next_offset"`  // 下一页偏移量
	EndFlag      int32      `json:"end_flag"`     // 是否到末页: 0否 1是
	UserFlowList []UserFlow `json:"UserFlowList"` // 流水列表
}

type GetUserInfoReq struct {
	UserId string `json:"user_id,optional"` // 用户ID
}

type GetUserInfoRsp struct {
	UserId  string `json:"user_id"` // 用户ID
	Name    string `json:"name"`    // 用户姓名
	Gender  int32  `json:"gender"`  // 性别: 1男 2女
	Age     int32  `json:"age"`     // 年龄
	Address string `json:"address"` // 联系地址
	Phone   string `json:"phone"`   // 手机号
	Email   string `json:"email"`   // 邮箱
	IdType  int32  `json:"id_type"` // 证件类型: 1身份证
	IdCard  string `json:"id_card"` // 证件号码
}

type GetUserTokenReq struct {
	UserId       string `json:"user_id,optional"`       // 用户ID
	Password     string `json:"password,optional"`      // 支付密码
	BusinessInfo string `json:"business_info,optional"` // 业务信息(申请token的业务上下文)
}

type GetUserTokenRsp struct {
	UserId    string `json:"user_id"`    // 用户ID
	UserToken string `json:"user_token"` // 用户token(后续登录凭证，时效1小时)
}

type HealthReq struct {
}

type HealthRsp struct {
}

type PayPreReq struct {
	UserId     string `json:"user_id,optional"`     // 用户ID
	MerchantId string `json:"merchant_id,optional"` // 商户ID
}

type PayPreRsp struct {
	UserId        string `json:"user_id"`        // 用户ID
	TransactionId string `json:"transaction_id"` // 预交易生成的交易单号
}

type RegUserReq struct {
	UserId   string `json:"user_id,optional"`  // 用户ID
	Password string `json:"password,optional"` // 支付密码
	Name     string `json:"name,optional"`     // 用户姓名
	Gender   int32  `json:"gender,optional"`   // 性别: 1男 2女
	Age      int32  `json:"age,optional"`      // 年龄
	Address  string `json:"address,optional"`  // 联系地址
	Phone    string `json:"phone,optional"`    // 手机号
	Email    string `json:"email,optional"`    // 邮箱
	IdType   int32  `json:"id_type,optional"`  // 证件类型: 1身份证
	IdCard   string `json:"id_card,optional"`  // 证件号码
}

type RegUserRsp struct {
	UserId string `json:"user_id"` // 用户ID
}

type UpdateUserInfoReq struct {
	UserId  string `json:"user_id,optional"` // 用户ID
	Name    string `json:"name,optional"`    // 用户姓名
	Gender  int32  `json:"gender,optional"`  // 性别: 1男 2女
	Age     int32  `json:"age,optional"`     // 年龄
	Address string `json:"address,optional"` // 地址
	Phone   string `json:"phone,optional"`   // 手机号
	Email   string `json:"email,optional"`   // 邮箱
	IdType  int32  `json:"id_type,optional"` // 证件类型: 1身份证
	IdCard  string `json:"id_card,optional"` // 证件号码
}

type UpdateUserInfoRsp struct {
	UserId string `json:"user_id"` // 用户ID
}

type UserFlow struct {
	TransactionId      string `json:"transaction_id"`       // 交易单号
	UserId             string `json:"user_id"`              // 用户ID
	CounterpartyUserId string `json:"counterparty_user_id"` // 交易对手方用户ID
	InoutType          int32  `json:"inout_type"`           // 收支类型: 1收入 2支出
	BizType            int32  `json:"biz_type"`             // 业务类型: 1充值/2转账/3提现/4支付消费
	Amount             int64  `json:"amount"`               // 交易金额, 单位分
	Balance            int64  `json:"balance"`              // 交易后余额, 单位分
	Desc               string `json:"desc"`                 // 交易描述
	Memo               string `json:"memo"`                 // 交易备注
	CreateTime         string `json:"create_time"`          // 交易时间
}
