// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type C2CTransferPreReq struct {
	BuyerUserId string `json:"buyer_user_id"`
}

type C2CTransferPreRsp struct {
	BuyerUserId   string `json:"buyer_user_id"`
	TransactionId string `json:"transaction_id"`
}

type GetUserBalanceInfoReq struct {
	UserId string `json:"user_id,optional"`
}

type GetUserBalanceInfoRsp struct {
	UserId  string `json:"user_id"`
	Balance int64  `json:"balance"`
	CurType int32  `json:"cur_type"`
}

type GetUserInfoReq struct {
	UserId string `json:"user_id,optional"`
}

type GetUserInfoRsp struct {
	UserId  string `json:"user_id"`
	Name    string `json:"name"`
	Gender  int32  `json:"gender"`
	Age     int32  `json:"age"`
	Address string `json:"address"`
	Phone   string `json:"phone"`
	Email   string `json:"email"`
	IdType  int32  `json:"id_type"`
	IdCard  string `json:"id_card"`
}

type HealthReq struct {
}

type HealthRsp struct {
}

type RegUserReq struct {
	UserId   string `json:"user_id,optional"`
	Password string `json:"password,optional"`
	Name     string `json:"name,optional"`
	Gender   int32  `json:"gender,optional"`
	Age      int32  `json:"age,optional"`
	Address  string `json:"address,optional"`
	Phone    string `json:"phone,optional"`
	Email    string `json:"email,optional"`
	IdType   int32  `json:"id_type,optional"`
	IdCard   string `json:"id_card,optional"`
}

type RegUserRsp struct {
	UserId string `json:"user_id"`
}

type UpdateUserInfoReq struct {
	UserId  string `json:"user_id,optional"`
	Name    string `json:"name,optional"`
	Gender  int32  `json:"gender,optional"`
	Age     int32  `json:"age,optional"`
	Address string `json:"address,optional"`
	Phone   string `json:"phone,optional"`
	Email   string `json:"email,optional"`
	IdType  int32  `json:"id_type,optional"`
	IdCard  string `json:"id_card,optional"`
}

type UpdateUserInfoRsp struct {
	UserId string `json:"user_id"`
}
