// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	pay_gate "github.com/starslipay/pay_gate/internal/handler/pay_gate"
	"github.com/starslipay/pay_gate/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/get_user_token",
				Handler: pay_gate.Get_user_tokenHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: pay_gate.HealthHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/reg_user",
				Handler: pay_gate.Reg_userHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/pay_gate"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/bank2c_do",
				Handler: pay_gate.Bank2c_doHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/bank2c_pre",
				Handler: pay_gate.Bank2c_preHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/c2c_transfer_do",
				Handler: pay_gate.C2c_transfer_doHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/c2c_transfer_pre",
				Handler: pay_gate.C2c_transfer_preHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/get_user_balance_info",
				Handler: pay_gate.Get_user_balance_infoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/get_user_flow",
				Handler: pay_gate.Get_user_flowHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/get_user_info",
				Handler: pay_gate.Get_user_infoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/update_user_info",
				Handler: pay_gate.Update_user_infoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/pay_gate"),
	)
}
